# Generated by Django 3.0.5 on 2020-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200508_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_image',
        ),
    ]
