# Generated by Django 3.0.5 on 2020-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.TextField(default='-'),
        ),
    ]
