# Generated by Django 3.0.5 on 2020-05-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='Telephone',
            field=models.TextField(default='000'),
        ),
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.TextField(default='fuckoff'),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='yut',
            field=models.TextField(),
        ),
    ]
