# Generated by Django 3.0.5 on 2020-05-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200506_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='Telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='yut',
            field=models.CharField(max_length=50),
        ),
    ]
